# Generated by Django 4.2.7 on 2024-08-07 10:37

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fullname", models.CharField(max_length=127)),
                ("birth_date", models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name="author",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("fullname"),
                name="fullname_unique",
            ),
        ),
    ]
