# Generated by Django 4.2.14 on 2024-08-10 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0003_book_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="image",
            field=models.URLField(blank=True, null=True),
        ),
    ]
