# Generated by Django 4.2.14 on 2024-08-10 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0004_book_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="description",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
