# Generated by Django 4.2.14 on 2024-08-10 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0006_alter_book_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="image",
            field=models.URLField(blank=True, null=True),
        ),
    ]
